name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100-rc.1.23463.5
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore